In [1]:
import torch

In [2]:
a = [1,2,3]
a

[1, 2, 3]

In [3]:
b = torch.ones(3)
b

tensor([1., 1., 1.])

In [4]:
c = torch.ones(3,4)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
b[1]

tensor(1.)

In [6]:
float(b[1])

1.0

In [7]:
b

tensor([1., 1., 1.])

In [8]:
b[2] = 3

In [9]:
b

tensor([1., 1., 3.])

In [10]:
d = 1
t1 = torch.tensor(d)
t1

tensor(1)

In [11]:
e = [1,2,3]
t2 = torch.tensor(e)
t2

tensor([1, 2, 3])

In [14]:
# shared memory
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

t = torch.from_numpy(arr)

arr[0][0] = 100

t

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [15]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
a[0][0] = 100
a

tensor([[100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

In [17]:
b = torch.zeros_like(a)
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
c = torch.ones(5,5)
c

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [20]:
d = torch.full([3,3],5)
d

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [21]:
points = torch.full([3,3], 6)
points

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [22]:
# save tensor as file
torch.save(points, "/Users/jiaronghe/Desktop/DigitalXi/askAVet/pytorch-project/points.t")

In [23]:
# load tensor from file
pp = torch.load("/Users/jiaronghe/Desktop/DigitalXi/askAVet/pytorch-project/points.t")
pp

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [25]:
# concat tensor
a = torch.ones(3,3)

cat_a1 = torch.cat([a,a], dim=0)
cat_a1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
cat_a2 = torch.cat([a,a], dim=1)
cat_a2

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [28]:
# stack tensor
a = torch.normal(0,1,(3,4))
b = torch.normal(0,1,(3,4))
cat_a3 = torch.stack([a,b], dim=0)
cat_a3

tensor([[[ 0.5094, -0.1769,  0.9791, -0.8293],
         [ 0.4172,  0.1932,  0.4900, -0.1744],
         [ 0.6092,  1.2582, -0.1639, -1.5293]],

        [[ 0.2119,  0.2462,  2.2426,  0.6646],
         [-1.1081, -0.3136, -0.4566, -0.6157],
         [ 0.8017,  0.6552,  0.3095, -1.1449]]])

In [31]:
# chunk tensor
a = torch.ones(3,3)
chunker_a = torch.chunk(a, 3, 1)
chunker_a

(tensor([[1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.]]),
 tensor([[1.],
         [1.],
         [1.]]))

In [32]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
idx = torch.tensor([0,2])
res = torch.index_select(points, dim=0, index=idx)
res

tensor([[4., 1.],
        [2., 1.]])

In [33]:
mask = points.ge(3)
mask

tensor([[ True, False],
        [ True,  True],
        [False, False]])

In [34]:
res = torch.masked_select(points, mask)
res

tensor([4., 5., 3.])

In [38]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage = points.storage()
points_storage

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [41]:
points = torch.tensor([[4.0,1.0,3.0,2.0],[5.0,3.0,7.0,8.0],[2.0,1.0,9.0,5.0],[3.0,8.0,4.0,5.0]])
points

tensor([[4., 1., 3., 2.],
        [5., 3., 7., 8.],
        [2., 1., 9., 5.],
        [3., 8., 4., 5.]])

In [42]:
second_point = points[1:,1:]
second_point

tensor([[3., 7., 8.],
        [1., 9., 5.],
        [8., 4., 5.]])

In [43]:
points.storage_offset()

0

In [44]:
second_point.storage_offset()

5

In [45]:
points.stride()

(4, 1)

In [46]:
second_point.stride()

(4, 1)

In [52]:
third_point = points[1:,1:].clone()
third_point

tensor([[3.],
        [1.]])

In [53]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [49]:
# transpose
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [50]:
id(points.storage()) == id(points_t.storage())

True

In [51]:
points.stride()

(2, 1)

In [54]:
points_t.stride()

(1, 2)